version: '3'
services:
    localstack:
        image: localstack/localstack
        networks:
            template:
                aliases:
                    - localstack
        ports:
            - "4576:4576"
            - "4566:4566"
        environment:
            - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
            - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_DEFAULT_OUTPUT=json
            - SERVICES=sqs
        volumes:
            - ./docker-entrypoint.sh:/docker-entrypoint-initaws.d/docker-entrypoint.sh
    
    app:
        depends_on:
            - localstack
        build: .
        networks:
            template:
                aliases:
                    - app
        ports:
            - "8080:8080"

networks:
    template: {}